"""adding tables

Revision ID: 05f3ec60eccd
Revises: 
Create Date: 2025-01-20 23:45:37.076594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f3ec60eccd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profession', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convention_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('convention_name', sa.String(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('convention_area_id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], name=op.f('fk_conventions_attendee_id_attendees')),
    sa.ForeignKeyConstraint(['convention_area_id'], ['convention_areas.id'], name=op.f('fk_conventions_convention_area_id_convention_areas')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conventions')
    op.drop_table('convention_areas')
    op.drop_table('attendees')
    # ### end Alembic commands ###
