"""fixing relationship between convention and attendee

Revision ID: b098db56ee51
Revises: 05f3ec60eccd
Create Date: 2025-01-23 00:27:46.845883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b098db56ee51'
down_revision = '05f3ec60eccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conventions', schema=None) as batch_op:
        batch_op.alter_column('convention_area_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('attendee_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conventions', schema=None) as batch_op:
        batch_op.alter_column('attendee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('convention_area_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
